### ISSUE TITLE
não consigo conectar a db

### ISSUE THREAD

**Issue by pedrofeliz90** [brunosribeiroo/wallet-api#11]
Olá, tentei conectar a db, de todas as formas, com xampp sem xampp, com o docker sem o docker e usando xampp. Nada.
sempre esse bendito erro aqui.

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/html/src/Infra/DBConnection.php:26 Stack trace: #0 /var/www/html/src/Infra/DBConnection.php(26): PDO->__construct('mysql:host=loca...', 'root', '') #1 /var/www/html/src/Infra/DBInit.php(80): Brunosribeiro\WalletApi\Infra\DBConnection->get() #2 /var/www/html/bootstrap.php(27): Brunosribeiro\WalletApi\Infra\iniciaDB->iniciaDB() #3 /var/www/html/public/index.php(3): include('/var/www/html/b...') #4 {main} thrown in /var/www/html/src/Infra/DBConnection.php on line 26

fiz todo tipo de pesquisa, mas sem sucesso, alguma idéia do que pode ser?

já troquei host para localhost para 127.0.0.1, testei conectar com as porta no código fonte, todo jeito.

**Comment by brunosribeiroo** [comment]
Aqui não consegui reproduzir esse erro, estou enfrentando um erro ao ler o arquivo autoload.php, consegui resolver apenas instalando manualmente em minha máquina.

Assim que possível irei subir a correção e provavelmente deve resolver o problema da conexão também.

**Comment by brunosribeiroo** [comment]
@pedrofeliz90  acabei de subir uma correção, assim que possível teste por favor.
Quanto a conexão, o host deve ser db assim como consta no arquivo .env.development, assim ele irá se conectar ao container db do docker-compose.
Depois me avise se deu certo, obrigado.

**Comment by pedrofeliz90** [comment]
Bom dia Bruno, estou usando db, estava usando o xampp, então, desinstalei achando que pudesse estar interferindo. Mas continuou a mesma coisa.

o docker esta conseguindo rodar a db, inclusive consigo acessa-la pelo phpmyadmin.

mas o site não consegue conectar apresentando aquele erro.

troquei localhost pra 127.0.0.1, fiz quase de tudo.

Estou sem acesso ao pc agora, assim q eu tiver acesso, já testo a nova atualização e dou o feedback

**Comment by brunosribeiroo** [comment]
Bom dia @pedrofeliz90, a conexão com o db deve ser 'db' e não localhost, pois eles estão dentro da mesma network do Docker. 
No arquivo ```environment.php```, deixe setado a variável 'development', segue o exemplo do return ```return $env['development'];```.
Assim que possível faça o teste com essa nova atualização e me dê um retorno por gentileza, caso não funcione, envie o trecho de código da sua conexão com o banco para analisarmos.
Obrigado.

**Comment by pedrofeliz90** [comment]
agora que entendi, o host tem que ficar DB, agora rodou normal.

Bem vindo à Wallet-API.

**Comment by pedrofeliz90** [comment]
porém, não mostrou as tabelas, não consigo saber se foram geradas.

**Comment by brunosribeiroo** [comment]
@pedrofeliz90 as tabelas vão estar no banco de dados, acessando o banco ela devem aparecer.
Você também pode testar as rotas, teste inicialmente essa rota: [/users](http://localhost:9000/users).
Ela irá buscar os usuários cadastrados, se ocorreu tudo bem ao criar as tabelas e a seeds, então você terá o retorno com os usuários.

**Comment by pedrofeliz90** [comment]
perfeito, ele está apenas em api, você não chegou a fazer layout para eles não né?
rodando show de bola agora

**Comment by brunosribeiroo** [comment]
Maravilha!

A aplicação é apenas a API, você pode utilizar o Postman ou outra ferramenta para testar as requisições.

Caso tenha interesse, fique a vontade para criar uma PR com o layout.

Vou fechar a issue já que foi resolvido, obrigado!
