### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Brunosribeiro\WalletApi\Controllers\CaixaController'

### ISSUE THREAD

**Issue by pedrofeliz90** [brunosribeiroo/wallet-api#12]
Olá Bruno, eu estou começando a adaptar algumas funcionalidades ao seu projeto, porém, esta dando esse erro, eu criei um Caixa, com funções de abrir e fechar caixa e mostrar caixas....

porém ele não esta rodando, ele não encontra a Classe  CaixaController, e esta tudo configurado as USE etc... eu joguei as mesmas functions para as páginas UserController, UserRepository e UserServices, e as funções funcionaram normalmente, porém quando rodo as CaixaController, CaixaRepository e CaixaServices da erro.

Fatal error: Uncaught Error: Class 'Brunosribeiro\WalletApi\Controllers\CaixaController' not found in C:\xampp\htdocs\wallet2\bootstrap.php:46 Stack trace: #0 C:\xampp\htdocs\wallet2\bootstrap.php(138): {closure}(NULL) #1 C:\xampp\htdocs\wallet2\public\index.php(3): include('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\wallet2\bootstrap.php on line 46

pra constar não estou usando docker, muito pesado aqui, rodei o servidor embutido do php.

**Comment by pedrofeliz90** [comment]
nos autoload's

**Comment by brunosribeiroo** [comment]
Olá Pedro, tudo bem ?

Verifiquei que já fechou a issue então acredito que tenha conseguido resolver, não cheguei a realizar testes.

Caso ainda esteja enfrentando problemas, me avise por favor para que eu possa lhe ajudar.

**Comment by pedrofeliz90** [comment]
Olá Bruno, nunca postei nada no GitHub, na realidade entendo bem pouco sobre isso aqui.
Parece que você liberou um fork pra mim? eu posso fazer as alterações lá.

onde ficam salvo os autoload, por que quando a pessoa baixa o código aqui, tem que instalar usando o composer, mas acredito que vai faltar as novas extensões que eu criei, se foi instalado de acordo suas autoload.

**Comment by pedrofeliz90** [comment]
A realidade que eu estou adaptando a sua api para uma api de cash game para poker, para administrar o cash

**Comment by brunosribeiroo** [comment]
Olá Pedro,

Como você criou um fork, agora você terá um clone desse repositório em seus repositórios do Github, nesse caso é só você realizar os commits para o seu repositório que é uma cópia desse, assim quem baixar através do seu, terá também as suas atualizações, e o meu repositório continua da mesma forma, sem as suas alterações.

Quem acessar pelo meu repositório, poderá visualizar os forks que foram feitos, e também poderão conferir o seu repositório caso ele esteja publico.

Então basta apenas você realizar os commits para o fork que você criou desse repositório, e prosseguir com as suas alterações.

**Comment by pedrofeliz90** [comment]
Bruno, estou com uma dificuldade, pra fazer uma query, talvez você possa me ajudar.
Estou querendo somar os registro das tabelas transacation_credit e debit e dar o return dos users em um determinado dia, é como se eu fosse dar o getBalanceById() mas mostrando todos os usuarios que movimentaram em um determinado dia. Deu de entender?

exemplificando:

users
id | nome
1 | Pedro
2 | Bruno
3 | Maria
4 | Joao
5 | Jose

trans_credit
id | id_user | value | created_at
1 | 1 | 50 | 2022-01-28 15:12:04
2 | 1 | 20 | 2022-01-28 16:12:04
3 | 2 | 20 | 2022-01-28 16:15:04
4 | 3 | 10 | 2022-01-28 17:12:04
5 | 3 | 30 | 2022-01-28 19:12:04
6 | 3 | 30 | 2022-01-29 19:13:04
7 | 3 | 30 | 2022-01-29 19:15:04
8 | 3 | 30 | 2022-01-29 19:17:04
9 | 3 | 30 | 2022-01-29 19:18:04

trans_debit
id | id_user | value | created_at
1 |   1        |  -30    | 2022-01-28 15:12:04
2 |   2        |  -5      | 2022-01-28 16:15:04
3 |   3        |  -55      | 2022-01-28 17:12:04
4 |   3        |  -55      | 2022-01-29 17:14:04
5 |   3        |  -55      | 2022-01-29 17:16:04
6 |   3        |  -55      | 2022-01-29 17:17:04
7 |   3        |  -55      | 2022-01-29 17:18:04


gostaria que a query dessa o return só do dia 28

nome: Pedro | Valor Total: 40
nome: Bruno | Valor Total: 15
nome: Maria | Valor Total: -25

**Comment by brunosribeiroo** [comment]
> Bruno, estou com uma dificuldade, pra fazer uma query, talvez você possa me ajudar.
> Estou querendo somar os registro das tabelas transacation_credit e debit e dar o return dos users em um determinado dia, é como se eu fosse dar o getBalanceById() mas mostrando todos os usuarios que movimentaram em um determinado dia. Deu de entender?
> 
> exemplificando:
> 
> users
> id | nome
> 1 | Pedro
> 2 | Bruno
> 3 | Maria
> 4 | Joao
> 5 | Jose
> 
> trans_credit
> id | id_user | value | created_at
> 1 | 1 | 50 | 2022-01-28 15:12:04
> 2 | 1 | 20 | 2022-01-28 16:12:04
> 3 | 2 | 20 | 2022-01-28 16:15:04
> 4 | 3 | 10 | 2022-01-28 17:12:04
> 5 | 3 | 30 | 2022-01-28 19:12:04
> 6 | 3 | 30 | 2022-01-29 19:13:04
> 7 | 3 | 30 | 2022-01-29 19:15:04
> 8 | 3 | 30 | 2022-01-29 19:17:04
> 9 | 3 | 30 | 2022-01-29 19:18:04
> 
> trans_debit
> id | id_user | value | created_at
> 1 |   1        |  -30    | 2022-01-28 15:12:04
> 2 |   2        |  -5      | 2022-01-28 16:15:04
> 3 |   3        |  -55      | 2022-01-28 17:12:04
> 4 |   3        |  -55      | 2022-01-29 17:14:04
> 5 |   3        |  -55      | 2022-01-29 17:16:04
> 6 |   3        |  -55      | 2022-01-29 17:17:04
> 7 |   3        |  -55      | 2022-01-29 17:18:04
> 
> 
> gostaria que a query dessa o return só do dia 28
> 
> nome: Pedro | Valor Total: 40
> nome: Bruno | Valor Total: 15
> nome: Maria | Valor Total: -25

Olá Pedro,

Essa dúvida é mais relacionada a banco de dados do que a aplicação. Vou fechar a issue devido ao assunto não ser relacionado.

Me envie um email por gentileza para: brunosribeiro@live.com ou me informe um contato seu, que tentarei te ajudar.

Abraços.
